### PR TITLE
Test cases for source maps

### PR DESCRIPTION
**Pull request by andreypopp**
Add test cases for source map functionality added in #23.

### CODE REVIEW

**Comment by andreypopp** [comment]
Cases are a little bit fragile, if you have a better idea how to test source map support I'd glad to fix them.

**Comment by andreypopp** [comment]
Let's merge this or... do you have any concerns?

**Comment by tj** [comment]
great! thanks

**Comment by tj** [comment]
squashed and merged as 9e2e590 :D

**Comment by tj** [comment]
i suppose we could use a little bit of documentation too haha forgot about that

**Comment by andreypopp** [comment]
@visionmedia this project doesn't seem to have docs at all :-) I assume jsdoc comment for `options` argument would be enough

**Comment by tj** [comment]
just a bit of markdown in the readme for `compress` and `sourcemap` would be sweet if you have a minute, or ill grab it after work :D

**Comment by kristoferjoseph** [comment]
@visionmedia Thanks for getting this feature in there!
@andreypopp Great work! Thanks for being on it.
Can't wait to show you what we are working on. :)
:beers:

**Pull request merged**
